version: '3.8'

services:
  # Redis for Celery
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  # Django Web Server with Celery
  web:
    build: .
    volumes:
      - .:/app
      - sqlite_data:/app/db  # Persist SQLite data
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

volumes:
  sqlite_data: