# Generated by Django 5.1.7 on 2025-03-21 01:09

import common.helpers
import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('query', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'search_query',
            },
            managers=[
                ('objects', common.helpers.BaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='VideoDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('video_id', models.CharField(max_length=50, unique=True)),
                ('title', models.TextField(db_index=True)),
                ('description', models.TextField(db_index=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('thumbnail_url', models.URLField()),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='video.searchquery')),
            ],
            options={
                'db_table': 'video_details',
            },
            managers=[
                ('objects', common.helpers.BaseManager()),
            ],
        ),
    ]
